test: &default

  # Credentials for REST APIs
  client_id: AQiilb1tViPkBOb04WAhvYHJSMvAUiUdS5T4CG-bfaGZdr0n9KkIUP-z2GCV201SuSFaYAOMBW9D_MCc
  client_secret: ECpq2GqijG_QX9XyDZIdpDkQq1JNJlHSeyD5zpC-HmFmInCU5PHSIBOqTK0fmeprIdJMEiyyQuQ5_ir9

  # Mode can be 'live' or 'sandbox'
  mode: sandbox
  sandbox_email_address: andrewj.allen-facilitator@mail.utoronto.ca

development:
  <<: *default

production:
  <<: *default
  mode: live
